config/routes.rb
Rails.application.routes.draw do
 root 'posts#index'
 get 'writer', to: 'pages#writer'
 get 'form', to: 'pages#form'

 resources :posts
 resources :categories, only: [:new, :create, :show]
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 5, maximum: 12}
  validates :summary, presence: true, length: {minimum: 15, maximum: 100}
  has_many :post_categories, dependent: :destroy
  has_many :posts, through: :post_categories
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
validates :title, presence: true, length: {minimum: 10, maximum: 50}
validates :summary, presence: true, length: {minimum: 30, maximum: 150}
validates :description, presence: true, length: {minimum: 100}
validate :picture_size

mount_uploader :picture, PictureUploader



 private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
belongs_to :post
belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "'#{@category.name}' category added successfully."
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
  end

  private

    def category_params
      params.require(:category).permit(:name, :summary)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def writer

  end

  def form

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Your post was created successfully"
      redirect_to posts_path
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Your post was updated successfully"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def show

  end


  private

    def post_params
      params.require(:post).permit(:title, :summary, :description, :picture, category_ids: [])
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<span class='quiet'><%= link_to category.name, category_path(category) %> </span>

app/views/categories/new.html.erb
<div class="container">
  <%= render "shared/page_title", title: "Add a Category" %>

  <%= render "shared/errors", obj: @category %>

  <%= form_for @category do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :summary %>
      <%= f.text_field :summary, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Add Category",  class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row pad-top">
    <div class="col-md-12 col-md-offset-0">
        <h1><%= render "shared/page_title", title: "Category: #{@category.name}" %></h1>
        <p><%= @category.summary %></p>
    </div>

    <div class="col-md-12">
      <h3 class="page-header">
       Current Articles written in the <em><%= "'#{@category.name.downcase}'" %></em> category <button type="button" class="btn btn-danger pull-right">View all</button>
    </h3>
    </div>

    <% @category.posts.each do |post| %>
    <div class="col-md-3 col-sm-6">
      <div class="thumbnail">
      <%= image_tag(post.picture.url, size: "750x500") if post.picture? %>
        <div class="caption">
          <h3><%= link_to post.title, post_path(post) %></h3>
          <p class="catc"><small><%= render post.categories %> | By KofiDesign</small></p>
          <p><%= post.summary %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
  <!--Main Footer here-->
  <div class="footer">
    <div class="container">
      <div class"row">

      </div>
    </div>
  </div>
</div>
</div>

<!--main footer-->
<div class="foot">
  <!-- Origional snipet by msurguy<http://bootsnipp.com/msurguy>, I editted his snipet so that it works with bootstrap 3.3 -->
<div class="container">
    <div class="row">
            <div class="col-xs-12 col-md-4">
                <ul class="list-unstyled">
                   <li><h3>BizzAfrica</h3><li>
                    <li> <p>Genius was not my idea - it was entirely Tom Lehman’s brainchild: he came up with it, and he built it. Similarly, Everipedia is not my idea at all - Sam,
                    Tedde and Travis took a year building that shit before I ever even saw it. In both cases, I got involved with an existing</p> </li>

                </ul>
            </div>

            <div class="col-md-8">
            <div class="row">
            <div class="col-xs-4 col-md-4">
                <ul class="list-unstyled">
                    <li><h3>Categories</h3><li>
                    <li><a href="#">Bizz of the week</a></li>
                    <li><a href="#">Top Bizz</a></li>
                    <li><a href="#">Discussions</a></li>
                    <li><a href="#">Links</a></li>
                </ul>
            </div>
            <div class="col-xs-4 col-md-4">
                <ul class="list-unstyled">
                    <li><h3>Content</h3><li>
                    <li><a href="#">Technology</a></li>
                    <li><a href="#">Business</a></li>
                    <li><a href="#">Start Ups</a></li>
                    <li><a href="#">Hackaton</a></li>
                    <li><a href="#">Events</a></li>
                </ul>
            </div>
            <div class="col-xs-4 col-md-4">
                <ul class="list-unstyled">
                    <li><h3>About Us</h3><li>
                    <li>BizzAfrica </li>
                    <li>1234 Osu</li>
                    <li>Accra, Ghana</li>
                    <ul class="list-unstyled list-inline pull-left">
                    <li class="fa fa-facebook-official fa-2x"><a href="#"></li>
                   <li class="fa fa-twitter-square fa-2x"><a href="#"></li>
                    <li class="fa fa-instagram fa-2x"><a href="#"></li>

                  </ul>



                </ul>
            </div>
          </div>
        </div>
    </div>
</div>
</div>
<!--main footer ends here-->

<!--sub footer-->
<div class="sub-footer">
  <div class="container">
    <div class="row">
            <div class="col-xs-8">
                <ul class="list-unstyled list-inline pull-left">
                    <li><a href="#">Terms of Service</a></li>
                    <li><a href="#">Contact Us</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Team</a></li>
                </ul>
            </div>
            <div class="col-xs-4">
                <p class="text-muted pull-right">&copy; <%= Time.now.year %> BizzAfrica. All rights reserved</p>
            </div>
        </div>
  </div>
</div>
<!--sub footer ends here-->

app/views/layouts/_header.html.erb
<!--Top navigation Bard added by @kofidesign-->
<nav class="navbar-fixed-top navbar navbar-default ati">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <h2><%= link_to "BizzAfrica", root_path, class: "navbar-brand11" %></h2>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", "" %></li>
        <li class="dropdown">
           <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
            Content <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
          <% Category.all.each do |category| %>
              <li><%= link_to category.name, category_path(category) %></li>
            <% end %>
          <li class='divider'></li>
          <li><%= link_to(new_category_path) do %>
              Add Category
            <% end %>
          </li>
          <li><%= link_to(new_post_path) do %>
              Create a Post
            <% end %>
          </li>
          </ul>
        </li>
        <li><%= link_to "Top Bizz", posts_path %></li>
        <li><%= link_to "Contact", "" %></li>
      </ul>

       <!--<form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--Top navigation ends here added by @kofidesign-->

app/views/layouts/_messages.html.erb
<div class="row post_show">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bizzafrica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
    <%= render "layouts/messages" %>

  <div class="container">
    <%= yield %>
  </div>

  <%= render "layouts/footer" %>

</body>
</html>

app/views/pages/writer.html.erb
<!--TOP summry with image and background image-->
<div class="writer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 ">
                <img src="http://placehold.it/200x200" alt="..." class="img-circle img-responsive">
            </div>
            <div class="col-lg-8">
               <h2>Charles Owusu Osei</h2>
               
                <div>
                <h4><i class="fa fa-globe"></i> Ghana</h4>    
                </div>
               
               <div>
                  <p><i class="fa fa-laptop"></i> http://bizzafrica.com</p> 
                </div>
               
               <div>
                <ul class="list-unstyled">
                    <ul class="list-unstyled list-inline pull-left">
                        <li class="fa fa-facebook-official fa-2x"></li>
                        <li class="fa fa-twitter-square fa-2x"></li>
                        <li class="fa fa-instagram fa-2x"></li>
                  </ul>
                </ul>
            </div>
            </div>
        </div>
    </div>
</div>
<!--TOP summry with image and background image ends here-->

<!--About me here. includes the top 5 posts-->
<div class="container">
    <div class="row pad-top">
        
        <div class="col-md-12 col-md-offset-0">
            <h1>About Me</h1>
            <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, nisi, saepe, mollitia, illo ipsa magni beatae debitis minima similique
                corporis consequatur at perspiciatis perferendis maiores excepturi nesciunt porro fugiat sunt!
                 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, nisi, saepe, mollitia, illo ipsa magni beatae debitis minima similique
                corporis consequatur at perspiciatis perferendis maiores excepturi nesciunt porro fugiat sunt!
                 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, nisi, saepe, mollitia, illo ipsa magni beatae debitis minima similique
                corporis consequatur at perspiciatis perferendis maiores excepturi nesciunt porro fugiat sunt!
                 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, nisi, saepe, mollitia,
            </p>
        </div>
        
        <!--top 5 posts here-->
        
       
        <div class="col-md-12">
            <h3 class="page-header">
               My Current Posts <button type="button" class="btn btn-danger pull-right">View all</button>
            </h3>
        </div>
    
        
        <div class="col-md-3 col-sm-6">
        <div class="thumbnail">
                    <img src="http://placehold.it/700x500" alt="">
                    <div class="caption">
                        <h3>The Future Of TV Is Apps, SAYS APPLE</h3>
                        <p class="catc"><small>Tech | By KofiDesign</small></p>
                        <p>Lorem ipsum dolor sit amet, consectetur dolor sit ame adipisicing.</p>
                    </div>
                </div>
      </div>
      
      <div class="col-md-3 col-sm-6">
        <div class="thumbnail">
                    <img src="http://placehold.it/700x500" alt="">
                    <div class="caption">
                        <h3>Facebook Test A Cragslist Killer</h3>
                        <p class="catc"><small>Tech | By KofiDesign</small></p>
                        <p>Lorem ipsum dolor sit amet, ctetur dolor sit ame adipisicing elit.</p>
                    </div>
                </div>
      </div>
      
      <div class="col-md-3 col-sm-6">
        <div class="thumbnail">
                    <img src="http://placehold.it/700x500" alt="">
                    <div class="caption">
                        <h3>Google’s Lack Of Product Isolation </h3>
                        <p class="catc"><small>Tech | By KofiDesign</small></p>
                        <p>Lorem ipsum dolor sit consectetur dolor sit ame adipisicing elit.</p>
                    </div>
                </div>
      </div>
      
      <div class="col-md-3 col-sm-6">
        <div class="thumbnail">
                    <img src="http://placehold.it/700x500" alt="">
                    <div class="caption">
                        <h3>How To Build Your Community</h3>
                        <p class="catc"><small>Tech | By KofiDesign</small></p>
                        <p>Lorem ipsum dolor sit amet, consec dolor sit ame adipisicing elit.</p>
                    </div>
                </div>
      </div>
        
        
       
       
        <!--top 5 posts here-->
        
    </div>
</div>
<!--About me ends here. includes the top 5 posts-->

app/views/posts/edit.html.erb
<div class="container">
  <%= render "shared/page_title", title: "Update Your Post" %>
    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<!--carouse Stars here -->
<div id="carousel-example-generic " class="carousel slide sli" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>

  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="http://pusaggh.org/images/gy.png" alt="...">
      <div class="carousel-caption">
       <h1>TOP FIVE LEADING STARTS UP IN GHANA</h1>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, eius, accusantium, sint quas expedita aliquam in iste non harum asperiores ratione minus maiores rem dolor magni vitae aut reprehenderit nesciunt.</p>
        <p><a href="#" class="btn btn-more btn-lg">Read More</a></p>
      </div>
    </div>
    <div class="item">
      <img src="http://pusaggh.org/images/yui.png" alt="...">
      <div class="carousel-caption">
       <h1>WHY MOST BUSINESS GET DISTRACTED IN THEIR INFANT STAGE </h1>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, eius, accusantium, sint quas expedita aliquam in iste non harum asperiores ratione minus maiores rem dolor magni vitae aut reprehenderit nesciunt.</p>
        <p><a href="#" class="btn btn-more btn-lg">Read More</a></p>
      </div>
    </div>
  </div>
</div>
<!--carouse ending here-->



<!--Main Content which includes sidebar (sidebar down there)-->
<div class="container">
  <div class="row">
  <div class="main-content">
    <!--content starts hers-->
  <div class="col-md-8 col-sm-8">
    <!--Big Boxes starts here-->
    <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-6 col-sm-6">
        <div class="thumbnail">
          <%= image_tag(post.picture.url, class: "gravatar") if post.picture? %>
          <div class="caption">
            <h3><%= link_to post.title, post_path(post) %></h3>
            <% if post.categories.any? %>
            <p class="catc"><small><%= render post.categories %> | By KofiDesign</small></p>
            <% end %>
            <p><%= post.summary %></p>
            <p><%= link_to "Edit", edit_post_path(post), class: "btn btn-success" %></p>
          </div>
        </div>
      </div>
      <% end %>
      <!--Boxes ends here-->

      <!--Small boxes starts here-->
      <% @posts.each do |post| %>
        <div class="col-md-6 col-sm-12">
          <div class="thumbnail2">
        <div class="media">
          <div class="media-left">
            <a href="#">
              <%= image_tag(post.picture.url, size: "130x130") if post.picture? %>
            </a>
              </div>
              <div class="media-body konko">
                <h5 class="media-heading"><strong><%= link_to post.title, post_path(post) %></strong></h5>
                <% if post.categories.any? %>
                  <p class="catc"><small><%= render post.categories %> | By KofiDesign</small></p>
                <% end %>
                 <p><%= link_to "Edit", edit_post_path(post), class: "btn btn-success" %></p>
                  <p><%= post.summary %></p>
              </div>
        </div>
        </div>
      </div>
      <% end %>
      <!--Small boxes ends here-->

      <!--horizontal boxes strats here-->
      <% @posts.each do |post| %>
      <div class="col-md-12 col-sm-12">
        <div class="thumbnail2">
      <div class="media">
        <div class="media-left hidden-xs hidden-sm">
          <a href="#">
            <%= image_tag(post.picture.url, size: "250x280") if post.picture? %>
          </a>
            </div>
            <div class="media-body konko2">
              <h3 class="media-heading"><%= link_to post.title, post_path(post) %></h3>
              <% if post.categories.any? %>
                <p class="catc"><small><%= render post.categories %> | By KofiDesign</small></p>
              <% end %>
               <p><%= link_to "Edit", edit_post_path(post), class: "btn btn-success" %></p>
               <p><%= post.summary %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
      <!--horizontal boxes ends here-->
    </div>
  </div>
</div>
<!--content Ends here hers-->



<!--Side bar area here-->
  <div class="col-md-4 col-sm-4 sidebar">
  <div class="sidebar">
   <h3 class="page-header">This Week Magazine</h3>
    <a href="#">
      <img class="img-responsive" src="http://pusaggh.org/images/mag1.jpg" alt="...">
    </a>
      <div class="col-md-12 col-sm-12">
      <h3 class="page-header pad-top">Top Bizz</h3>
      <% @posts.each do |post| %>
      <div class="medias">
        <div class="media-left hidden-sm">
          <a href="#">
            <%= image_tag(post.picture.url, size: "130x130") if post.picture? %>
          </a>
            </div>
            <div class="media-body konko3">
              <h5 class="media-heading"><strong><%= link_to post.title, post_path(post) %></strong></h5>
               <p class="catc"><small>Social | By KofiDesign</small></p>
                <p><%= post.summary %></p>
            </div>
        </div>
      <% end %>
      </div>


      <div class="col-sm-12">
        <h3 class=" pad-top"> <a href="#" class="btn btn-more"><i class="fa fa-bolt"></i> Trending Tech</a></h3>
         <ul class="list-unstyled">
         <% @posts.each do |post| %>
          <li><h5><strong><%= link_to post.title, post_path(post) %></strong></h5></li>
          <% end %>
          </ul>
          <hr>
      </div>
    <!--facebook plug area-->
      <div class="col-sm-12 pad-top hidden-sm">
        <div class="fb-page" data-href="https://www.facebook.com/facebook" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/facebook"><a href="https://www.facebook.com/facebook">Facebook</a></blockquote></div></div>
      </div>
    <!--facebook plug area-->

    <div class="col-sm-12 pad-top pad-down">
        <a href="#">
          <img class="img-responsive" src="http://pusaggh.org/images/mag1.jpg" alt="...">
          </a>
      </div>
  </div>
</div>
  <!--Side bar area ending  here-->

<!--Main Content which includes sidebar  (sidebar down there) Ends here-->

<!--Added it because of the facebook page on the site-->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=175969142740879";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!--Added it because of the facebook page on the site-->

app/views/posts/new.html.erb
<div class="container">
  <%= render "shared/page_title", title: "Create a Post" %>
    <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="post_show">
    <!--Single Show page-->
    <div class="container" >
      <div class="row">
        <div class="col-md-8">
          <h2><%= @post.title %></h2>
          <% if @post.categories.any? %>
            <p class="catc"><small><%= render @post.categories %> | By KofiDesign</small></p>
          <% end %>
          <div class="show_post">
            <%= image_tag(@post.picture.url, class: "img-responsive") if @post.picture? %>
          </div>
          <p class="pull-right"><%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-success" %></p>
          <p class="blog-post pad-top "><%= @post.description %></p>

         <!--comment box here-->

<div class="form-comment pad-top">
  <h3>Leave Your Comment</h3>
  <form role="form">
    <div class="row">
      <div class="form-group col-md-4">
        <input class="form-control input-lg" placeholder="Name..">
      </div>
      <div class="form-group col-md-4">
        <input class="form-control input-lg" placeholder="Email..">
      </div>
      <div class="form-group col-md-4">
        <input class="form-control input-lg" placeholder="Url..">
      </div>
      <div class="form-group col-md-12">
        <textarea class="form-control" rows="8" placeholder="Messages.."></textarea>
      </div>
      <div class="form-group col-md-4">
        <button class="btn btn-lg btn-more btn-block">Comment</button>
      </div>
    </div>
  </form>
</div>

<div class="media">
<a class="pull-left" href="#">
    <img class="media-object" src="http://placehold.it/64x64" alt="">
</a>
<div class="media-body konko3">
  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
</div>
</div>

<div class="media">
<a class="pull-left" href="#">
  <img class="media-object" src="http://placehold.it/64x64" alt="">
</a>
  <div class="media-body konko3">
    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
  </div>
</div>


         <!--comment box here-->
</div>



    <!--Side bar area here-->
  <div class="col-md-4 col-sm-4 sidebar">
  <div class="sidebar">
   <h3 class="page-header">This Week Magazine</h3>
    <a href="#">
          <img class="img-responsive" src="http://pusaggh.org/images/mag1.jpg" alt="...">
    </a>


      <div class="col-md-12 col-sm-12">
      <h3 class="page-header pad-top">Top Bizz</h3>
      <div class="medias">
        <div class="media-left hidden-sm">
          <a href="#">
            <img class="media-object" src="http://placehold.it/130x130" alt="">
          </a>
            </div>
            <div class="media-body konko3">
              <h5 class="media-heading"><strong>Israel conducting slow motion genocide</strong></h5>
               <p class="catc"><small>Social | By KofiDesign</small></p>
                <p>Latest interview with Al Etejah TV about racist</p>
            </div>
          </div>
      </div>

      <div class="col-md-12 col-sm-12">
      <div class="medias">
        <div class="media-left hidden-sm">
          <a href="#">
            <img class="media-object" src="http://placehold.it/130x130" alt="">
          </a>
            </div>
            <div class="media-body konko3">
              <h5 class="media-heading"><strong>Israel conducting slow motion genocide</strong></h5>
               <p class="catc"><small>Social | By KofiDesign</small></p>
                <p>Latest interview with Al Etejah TV about racist</p>
            </div>
          </div>
      </div>

       <div class="col-md-12 col-sm-12">
      <div class="medias">
        <div class="media-left hidden-sm">
          <a href="#">
            <img class="media-object" src="http://placehold.it/130x130" alt="">
          </a>
            </div>
            <div class="media-body konko3">
              <h5 class="media-heading"><strong>Israel conducting slow motion genocide</strong></h5>
               <p class="catc"><small>Social | By KofiDesign</small></p>
                <p>Latest interview with Al Etejah TV about racist</p>
            </div>
          </div>
      </div>

      <div class="col-sm-12">
      <div class="medias">
        <div class="media-left hidden-sm">
          <a href="#">
            <img class="media-object" src="http://placehold.it/130x130" alt="">
          </a>
            </div>
            <div class="media-body konko3">
              <h5 class="media-heading"><strong>Israel conducting slow motion genocide</strong></h5>
               <p class="catc"><small>Social | By KofiDesign</small></p>
                <p>Latest interview with Al Etejah TV about racist</p>
            </div>
          </div>
      </div>


      <div class="col-sm-12">
        <h3 class=" pad-top"> <a href="#" class="btn btn-more"><i class="fa fa-bolt"></i> Trending Tech</a></h3>
         <ul class="list-unstyled">
                    <li><a href="#"> <h5><strong>Israel conducting slow motion genocide</strong></h5></a></li>
                    <li><a href="#"> <h5><strong>Facebook Test A Cragslist Killer</strong></h5></a></li>
                    <li><a href="#"> <h5><strong>Google, Facebook, Yahoo And Verizon</strong></h5></a></li>
                    <li><a href="#"> <h5><strong>The Future Of TV Is Apps, SAYS APPLE</strong></h5></a></li>
                    <li><a href="#"> <h5><strong>Israel conducting slow motion genocide</strong></h5></a></li>


          </ul>
          <hr>
      </div>

    <!--facebook plug area-->
      <div class="col-sm-12 pad-top hidden-sm">
        <div class="fb-page" data-href="https://www.facebook.com/facebook" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/facebook"><a href="https://www.facebook.com/facebook">Facebook</a></blockquote></div></div>
      </div>
    <!--facebook plug area-->

    <div class="col-sm-12 pad-top pad-down">
        <a href="#">
          <img class="img-responsive" src="http://pusaggh.org/images/mag1.jpg" alt="...">
          </a>
      </div>



  </div>
  </div>
  <!--Side bar area ending  here-->

      </div>
    </div>

    <!--Single Show page -->
</div>